### PR TITLE
Updating model to gpt-4o-mini

### PR DESCRIPTION
**Pull request by bilalba**
Inspired by https://github.com/Acters/humanify-ng/tree/GPT4o, I decided to make a PR after testing some of the changes from there. 

The openai sdk is updated to version 4.52.7 addressing #19

gpt-tokenizer is used instead of gpt3-encoder addressing #5 

I am seeking to address #4 with a good enough solution of using gpt-4o-mini with the assumption that it would be intelligent enough.

I have updated the model to gpt-4o-mini and removed the option to use 4k context, since gpt-4o-mini is already cheap enough and is not constrained by context length. 

However, I have still capped the context at 32k. In my testing, Using a larger context would not result in enough variable name replacements. I.e. it would only change a few function and variable names.

### CODE REVIEW

**Comment by 0xdevalias** [comment]
> I also noticed you decreased the number of tokens to 32k. how does this change affect it? is the 128k limit too much even with the soft cap reducing it to be at 1/4 the amount of tokens? Or is it because the output tokens are at 16k for the 4o-mini versions?

@Acters Read the last paragraph of the PR description which explains this:

> However, I have still capped the context at 32k. In my testing, Using a larger context would not result in enough variable name replacements. I.e. it would only change a few function and variable names.

**Comment by bilalba** [comment]
@Acters Did you see it return all the variable names replaced when you ran it with 128k context? I only saw a few. I presume that it only tackles a few problems every query, despite having all the context and output tokens. 

I do like your idea about using threads to fill the context and querying it multiple times, so it gets a chance to 'think' and address all the replacements.

I also really like your idea on Parallel Function Calling. I imagine it would serve as a significant improvement. 

Would you like to add those features as a part of another PR? I believe all of these three things are separate enhancements that can go on top of each other. 

@jehna Would appreciate your input as the owner and maintainer of this repository.

**Comment by 0xdevalias** [comment]
> Would you like to add those features as a part of another PR? I believe all of these three things are separate enhancements that can go on top of each other.

@bilalba @Acters While including them in a new PR is probably a good idea, updating the OpenAI SDK version is likely going to be a blocker on all of them:

> The openai sdk is updated to version 4.52.7 addressing #19

**Comment by jehna** [comment]
Hey! Seems that this PR got auto-closed because of the release of v2.

Thank you for your hard work and interest on improving humanify, especially @bilalba for maintaining a modernised fork while I've been unresponsive.

The v2 has now dependabot and automated merges for dependency updates that pass the tests, so dependencies should be easier to be kept up to date. I've also made `gpt-4o-mini` the default model and added the long awaited JSON mode with the new [structured outputs](https://openai.com/index/introducing-structured-outputs-in-the-api/).

The v2 does not count token anymore, but it uses the same AST-based precise approach that's been working for local renames. This should ensure that all the variable names are renamed, while not overloading the context limit of gpt-4o and others. I've experienced that some models (like Claude Opus) is much better at utilizing the full context window than others (like gpt-4o). By directing the LLM's focus to a small part that's only the fraction of its context window has worked the best in my testing. The v2 window size is super small now, but I'd be happy to increase it (or make it configurable via cli flag) if needed.

**Comment by 0xdevalias** [comment]
> Seems that this PR got auto-closed because of the release of v2.

I think that was probably because of this:

> Also, it looks like the v2 branch may have been started from scratch (first commit: https://github.com/jehna/humanify/commit/e9770a63461835aac2e23fe0b0761610046cc634), rather than continuing on from the historical branch (https://github.com/jehna/humanify/tree/v1). Why was that?
> 
> _Originally posted by @0xdevalias in https://github.com/jehna/humanify/issues/31#issuecomment-2282986825_

**Pull request closed without merging**
